
services:
  pgdatabase:
    image: postgres:13.3
    container_name: pgdatabase
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    ports:
      - 5432:5432
    volumes:
      - ./ny_taxi_postgres_data:/var/lib/postgresql/data
    networks:
      - ny_taxi_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - 8080:80
    volumes:
      - ./ny_taxi_pgadmin_data:/var/lib/pgadmin
    networks:
      - ny_taxi_network

networks:
  ny_taxi_network:


